version: '2'
services:
  web:
    build: ./app
    ports:
      - "80:3000"
    environment:
      - DATABASE_MYSQL_HOSTNAME=database
      - DATABASE_MYSQL_PORT=3306
      - DATABASE_MYSQL_USERNAME=mysqlworker
      - DATABASE_MYSQL_PASSWORD=mysqlworker
      - DATABASE_MYSQL_DATABASE=application
    links:
      - database
  database:
    image: mariadb:10.3
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_HOSTNAME=database
      - MYSQL_PORT=3306
      - MYSQL_USER=mysqlworker
      - MYSQL_PASSWORD=mysqlworker
      - MYSQL_DATABASE=application
    ports:
      - "3306:3306"
    volumes:
      - ./db/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d